# Generated by Django 5.2 on 2025-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreoccupationEnvironnementale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pourcentage_repondants', models.FloatField()),
                ('nombre_repondants', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EnvironmentalData',
        ),
    ]
