# Generated by Django 5.2 on 2025-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_preoccupationenvironnementale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureTerrestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('ecart', models.FloatField()),
            ],
        ),
    ]
