# Generated by Django 5.2 on 2025-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_temperatureocean'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauOcean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('niveau', models.FloatField()),
            ],
        ),
    ]
