# Generated by Django 5.2 on 2025-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_niveauocean'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEmissionGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('n2o', models.FloatField()),
                ('gaz_fluores', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
