# Generated by Django 5.2 on 2025-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sourceemissionges'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesEspecesMenacees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_especes_etudiees', models.IntegerField()),
                ('total_especes_menacees', models.IntegerField()),
                ('proportion_menacees', models.FloatField()),
            ],
        ),
    ]
