# Generated by Django 5.2 on 2025-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_statistiquesespecesmenacees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeceMenacee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('part_menacee', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StatistiquesEspecesMenacees',
        ),
    ]
