# Generated by Django 5.2 on 2025-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_especemenacee_delete_statistiquesespecesmenacees'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMenace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nombre_restant', models.IntegerField()),
            ],
        ),
    ]
